export const GAME_PLAY_FRIEND = "GAME_PLAY_FRIEND";
export const CREATE_GAME = "CREATE_GAME";
export const ACT_GAME = "ACT_GAME";
export const SUM_POINTS = "SUM_POINTS";

export const ADD_USER_CHAT = "ADD_USER_CHAT";

export const GET_NOTIFICATION_GAME = "GET_NOTIFICATION_GAME";
export const POST_NOTIFICATION_GAME = "POST_NOTIFICATION_GAME";
export const DELETE_NOTIFICATION_GAME = "DELETE_NOTIFICATION_GAME";

export const DELETE_USER_SESION = "DELETE_USER_SESION";

export const ADD_PROFILE = "GET_PROFILE";
export const DEL_PROFILE = "DEL_PROFILE";


export const ACT_DATA_PLAYERS = "ACT_DATA_PLAYERS";

export const CREATE_DATA_GAME = "CREATE_DATA_GAME";
export const SUM_QUATITY_RES = "SUM_QUATITY_RES";
export const ACT_DATA_GAME = "ACT_DATA_GAME";
export const RESET_DATA_GAME = "RESET_DATA_GAME";


